language: ruby
rvm:
- 2.7.0
node_js:
    - 12.16.1
script:
    - export RUBYOPT='-W0'
    - bundle install
    - RAILS_ENV=test bundle exec rails webpacker:compile
    - bundle exec rake db:migrate RAILS_ENV=test
    - bundle exec rake cucumber
